env:
  browser: true
plugins:
  - jsdoc
extends:
  - plugin:jsdoc/recommended
rules:
  jsdoc/no-types: error
  jsdoc/require-returns-type: 'off'
  jsdoc/require-param-type: 'off'
  jsdoc/check-tag-names:
    - warn
    - definedTags:
        - internal
settings:
  jsdoc:
    ignorePrivate: true
    ignoreInternal: true
