[package]
name = "ruffle_render_common_tess"
version = "0.1.0"
authors = ["Mike Welsh <mwelsh@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
log = "0.4"
lyon = "0.17.10"

[dependencies.ruffle_core]
path = "../../core"
default-features = false
